// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartTransportation.DAL.Models;

[Index("BookingId", Name = "IX_BookingPassengers_BookingID")]
public partial class BookingPassenger
{
    [Key]
    [Column("BookingPassengerID")]
    public int BookingPassengerId { get; set; }

    [Column("BookingID")]
    public int BookingId { get; set; }

    [Column("PassengerUserID")]
    public int PassengerUserId { get; set; }

    public int? SeatNumber { get; set; }

    public bool CheckInStatus { get; set; }

    [ForeignKey("BookingId")]
    [InverseProperty("BookingPassengers")]
    public virtual Booking Booking { get; set; }

    [ForeignKey("PassengerUserId")]
    [InverseProperty("BookingPassengers")]
    public virtual User PassengerUser { get; set; }
}