// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartTransportation.DAL.Models;

[Index("TripId", Name = "IX_Bookings_TripID")]
[Index("BookerUserId", Name = "IX_Bookings_UserID")]
public partial class Booking
{
    [Key]
    [Column("BookingID")]
    public int BookingId { get; set; }

    [Column("TripID")]
    public int TripId { get; set; }

    [Column("BookerUserID")]
    public int BookerUserId { get; set; }

    public DateTime BookingDate { get; set; }

    [Required]
    [StringLength(30)]
    public string BookingStatus { get; set; }

    [Required]
    [StringLength(30)]
    public string PaymentStatus { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal TotalAmount { get; set; }

    public int SeatsCount { get; set; }

    [ForeignKey("BookerUserId")]
    [InverseProperty("Bookings")]
    public virtual User BookerUser { get; set; }

    [InverseProperty("Booking")]
    public virtual ICollection<BookingPassenger> BookingPassengers { get; set; } = new List<BookingPassenger>();

    [InverseProperty("Booking")]
    public virtual ICollection<BookingSegment> BookingSegments { get; set; } = new List<BookingSegment>();

    [InverseProperty("Booking")]
    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    [ForeignKey("TripId")]
    [InverseProperty("Bookings")]
    public virtual Trip Trip { get; set; }
}