// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartTransportation.DAL.Models;

[Index("BookingId", Name = "IX_BookingSegments_BookingID")]
public partial class BookingSegment
{
    [Key]
    [Column("BookingSegmentID")]
    public int BookingSegmentId { get; set; }

    [Column("BookingID")]
    public int BookingId { get; set; }

    [Column("SegmentID")]
    public int SegmentId { get; set; }

    [ForeignKey("BookingId")]
    [InverseProperty("BookingSegments")]
    public virtual Booking Booking { get; set; }

    [ForeignKey("SegmentId")]
    [InverseProperty("BookingSegments")]
    public virtual RouteSegment Segment { get; set; }
}