// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartTransportation.DAL.Models;

[Index("SegmentId", Name = "IX_MapLocations_SegmentID")]
public partial class MapLocation
{
    [Key]
    [Column("LocationID")]
    public int LocationId { get; set; }

    [Column("SegmentID")]
    public int SegmentId { get; set; }

    [Column(TypeName = "decimal(9, 6)")]
    public decimal? Latitude { get; set; }

    [Column(TypeName = "decimal(9, 6)")]
    public decimal? Longitude { get; set; }

    [StringLength(150)]
    public string Description { get; set; }

    public int? StopOrder { get; set; }

    [Column("GooglePlaceID")]
    [StringLength(150)]
    public string GooglePlaceId { get; set; }

    [StringLength(300)]
    public string GoogleAddress { get; set; }

    [ForeignKey("SegmentId")]
    [InverseProperty("MapLocations")]
    public virtual RouteSegment Segment { get; set; }
}