// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartTransportation.DAL.Models;

public enum PaymentStatus
{
    Pending,
    Succeeded,
    Failed,
    Canceled
}

public class Payment
{
    [Key]
    [Column("PaymentID")]
    public int PaymentId { get; set; }

    [Column("BookingID")]
    public int BookingId { get; set; }

    [Column(TypeName = "decimal(10,2)")]
    public decimal Amount { get; set; }      // %5 platformfee amount charged via Stripe

    [Required]
    [StringLength(10)]
    public string Currency { get; set; } = "EGP";

    // Stripe PaymentIntent ID (e.g. "pi_3Nc...").
    [StringLength(100)]
    public string StripePaymentIntentId { get; set; }

    [Required]
    [StringLength(20)]
    public string Status { get; set; } = PaymentStatus.Pending.ToString();

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? PaidAt { get; set; }

    [StringLength(255)]
    public string? LastError { get; set; }

    [ForeignKey("BookingId")]
    public virtual Booking Booking { get; set; }
}