// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartTransportation.DAL.Models;

public partial class Rating
{
    [Key]
    [Column("RatingID")]
    public int RatingId { get; set; }

    [Column("TripID")]
    public int TripId { get; set; }

    [Column("UserID")]
    public int UserId { get; set; }

    public int? Score { get; set; }

    [StringLength(255)]
    public string Comment { get; set; }

    public DateTime CreatedAt { get; set; }

    [ForeignKey("TripId")]
    [InverseProperty("Ratings")]
    public virtual Trip Trip { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Ratings")]
    public virtual User User { get; set; }
}