// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartTransportation.DAL.Models;

public partial class RouteSegment
{
    [Key]
    [Column("SegmentID")]
    public int SegmentId { get; set; }

    [Column("RouteID")]
    public int RouteId { get; set; }

    public int SegmentOrder { get; set; }

    [Required]
    [StringLength(100)]
    public string StartPoint { get; set; }

    [Required]
    [StringLength(100)]
    public string EndPoint { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? DistanceKm { get; set; }

    public int? EstimatedMinutes { get; set; }

    [InverseProperty("Segment")]
    public virtual ICollection<BookingSegment> BookingSegments { get; set; } = new List<BookingSegment>();

    [InverseProperty("Segment")]
    public virtual ICollection<MapLocation> MapLocations { get; set; } = new List<MapLocation>();

    [ForeignKey("RouteId")]
    [InverseProperty("RouteSegments")]
    public virtual Route Route { get; set; }
}