// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartTransportation.DAL.Models;

[Index("DriverId", Name = "IX_Trips_DriverID")]
[Index("RouteId", Name = "IX_Trips_RouteID")]
public partial class Trip
{
    [Key]
    [Column("TripID")]
    public int TripId { get; set; }

    [Column("RouteID")]
    public int RouteId { get; set; }

    [Column("DriverID")]
    public int DriverId { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal PricePerSeat { get; set; }

    public int AvailableSeats { get; set; }

    [Required]
    [StringLength(30)]
    public string Status { get; set; }

    [StringLength(255)]
    public string Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    [InverseProperty("Trip")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    [ForeignKey("DriverId")]
    [InverseProperty("Trips")]
    public virtual User Driver { get; set; }

    [InverseProperty("Trip")]
    public virtual ICollection<Rating> Ratings { get; set; } = new List<Rating>();

    [ForeignKey("RouteId")]
    [InverseProperty("Trips")]
    public virtual Route Route { get; set; }

    [InverseProperty("Trip")]
    public virtual ICollection<TripLocation> TripLocations { get; set; } = new List<TripLocation>();
}