// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartTransportation.DAL.Models;

[Index("TripId", Name = "IX_TripLocations_TripID")]
public partial class TripLocation
{
    [Key]
    [Column("TripLocationID")]
    public int TripLocationId { get; set; }

    [Column("TripID")]
    public int TripId { get; set; }

    [Column(TypeName = "decimal(9, 6)")]
    public decimal? Latitude { get; set; }

    [Column(TypeName = "decimal(9, 6)")]
    public decimal? Longitude { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? Speed { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? Heading { get; set; }

    [Column("GooglePlaceID")]
    [StringLength(150)]
    public string GooglePlaceId { get; set; }

    [StringLength(300)]
    public string GoogleAddress { get; set; }

    public DateTime RecordedAt { get; set; }

    [ForeignKey("TripId")]
    [InverseProperty("TripLocations")]
    public virtual Trip Trip { get; set; }
}