// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartTransportation.DAL.Models;

public partial class UserType
{
    [Key]
    [Column("UserTypeID")]
    public int UserTypeId { get; set; }

    [Required]
    [StringLength(50)]
    public string TypeName { get; set; }

    [StringLength(200)]
    public string Description { get; set; }

    [InverseProperty("UserType")]
    public virtual ICollection<User> Users { get; set; } = new List<User>();
}