// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartTransportation.DAL.Models;

[Index("UserId", Name = "UQ__UserProf__1788CCAD0CBF73C7", IsUnique = true)]
public partial class UserProfile
{
    [Key]
    [Column("UserProfileID")]
    public int UserProfileId { get; set; }

    [Column("UserID")]
    public int UserId { get; set; }

    [StringLength(150)]
    public string FullName { get; set; }

    [StringLength(50)]
    public string Phone { get; set; }

    [StringLength(250)]
    public string Address { get; set; }

    [StringLength(100)]
    public string City { get; set; }

    [StringLength(100)]
    public string Country { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    [StringLength(20)]
    public string Gender { get; set; }

    [StringLength(500)]
    public string ProfilePhotoUrl { get; set; }

    public bool IsDriver { get; set; }

    [StringLength(100)]
    public string DriverLicenseNumber { get; set; }

    public DateOnly? DriverLicenseExpiry { get; set; }

    [Column(TypeName = "decimal(3, 2)")]
    public decimal? DriverRating { get; set; }

    public bool IsDriverVerified { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("UserProfile")]
    public virtual User User { get; set; }
}