// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartTransportation.DAL.Models;

[Index("PlateNumber", Name = "UQ__Vehicles__03692624491BD79E", IsUnique = true)]
public partial class Vehicle
{
    [Key]
    [Column("VehicleID")]
    public int VehicleId { get; set; }

    [Column("DriverID")]
    public int DriverId { get; set; }

    [StringLength(100)]
    public string VehicleMake { get; set; }

    [StringLength(100)]
    public string VehicleModel { get; set; }

    public int? VehicleYear { get; set; }

    [StringLength(50)]
    public string PlateNumber { get; set; }

    [StringLength(50)]
    public string Color { get; set; }

    public int SeatsCount { get; set; }

    [StringLength(100)]
    public string VehicleLicenseNumber { get; set; }

    public DateOnly? VehicleLicenseExpiry { get; set; }

    public bool IsVerified { get; set; }

    public DateTime CreatedAt { get; set; }

    [ForeignKey("DriverId")]
    [InverseProperty("Vehicles")]
    public virtual User Driver { get; set; }
}