// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartTransportation.DAL.Models;

[Table("Weather")]
[Index("RouteId", Name = "IX_Weather_RouteID")]
public partial class Weather
{
    [Key]
    [Column("WeatherID")]
    public int WeatherId { get; set; }

    [Column("RouteID")]
    public int RouteId { get; set; }

    public DateOnly WeatherDate { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? Temperature { get; set; }

    [StringLength(100)]
    public string Condition { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? WindSpeed { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? Humidity { get; set; }

    [ForeignKey("RouteId")]
    [InverseProperty("Weathers")]
    public virtual Route Route { get; set; }
}