// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SmartTransportation.DAL.Models;

public partial class TransportationContext : DbContext
{
    public TransportationContext(DbContextOptions<TransportationContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<BookingPassenger> BookingPassengers { get; set; }

    public virtual DbSet<BookingSegment> BookingSegments { get; set; }

    public virtual DbSet<MapLocation> MapLocations { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<Rating> Ratings { get; set; }

    public virtual DbSet<Route> Routes { get; set; }

    public virtual DbSet<RouteSegment> RouteSegments { get; set; }

    public virtual DbSet<Trip> Trips { get; set; }

    public virtual DbSet<TripLocation> TripLocations { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserProfile> UserProfiles { get; set; }

    public virtual DbSet<UserType> UserTypes { get; set; }

    public virtual DbSet<Vehicle> Vehicles { get; set; }

    public virtual DbSet<Weather> Weathers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Booking>(entity =>
        {
            entity.HasKey(e => e.BookingId).HasName("PK__Bookings__73951ACDD89388C5");

            entity.Property(e => e.BookingDate).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.BookingStatus).HasDefaultValue("Pending");
            entity.Property(e => e.PaymentStatus).HasDefaultValue("Pending");
            entity.Property(e => e.SeatsCount).HasDefaultValue(1);

            entity.HasOne(d => d.BookerUser).WithMany(p => p.Bookings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Bookings_User");

            entity.HasOne(d => d.Trip).WithMany(p => p.Bookings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Bookings_Trip");
        });

        modelBuilder.Entity<BookingPassenger>(entity =>
        {
            entity.HasKey(e => e.BookingPassengerId).HasName("PK__BookingP__34702EA702D62CCE");

            entity.HasOne(d => d.Booking).WithMany(p => p.BookingPassengers).HasConstraintName("FK_BookingPassengers_Booking");

            entity.HasOne(d => d.PassengerUser).WithMany(p => p.BookingPassengers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BookingPassengers_User");
        });

        modelBuilder.Entity<BookingSegment>(entity =>
        {
            entity.HasKey(e => e.BookingSegmentId).HasName("PK__BookingS__586D1F1A5D2A763B");

            entity.HasOne(d => d.Booking).WithMany(p => p.BookingSegments).HasConstraintName("FK_BookingSegments_Booking");

            entity.HasOne(d => d.Segment).WithMany(p => p.BookingSegments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BookingSegments_Segment");
        });

        modelBuilder.Entity<MapLocation>(entity =>
        {
            entity.HasKey(e => e.LocationId).HasName("PK__MapLocat__E7FEA4773DBDE9E4");

            entity.HasOne(d => d.Segment).WithMany(p => p.MapLocations).HasConstraintName("FK_MapLocations_Segment");
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.NotificationId).HasName("PK__Notifica__20CF2E327044E76E");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.User).WithMany(p => p.Notifications)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Notifications_User");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.PaymentId).HasName("PK__Payments__9B556A58CD4B6218");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Currency).HasDefaultValue("EGP");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Status).HasDefaultValue("Pending");

            entity.HasOne(d => d.Booking).WithMany(p => p.Payments).HasConstraintName("FK_Payments_Booking");
        });

        modelBuilder.Entity<Rating>(entity =>
        {
            entity.HasKey(e => e.RatingId).HasName("PK__Ratings__FCCDF85C0B0A9020");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.Trip).WithMany(p => p.Ratings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Ratings_Trip");

            entity.HasOne(d => d.User).WithMany(p => p.Ratings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Ratings_User");
        });

        modelBuilder.Entity<Route>(entity =>
        {
            entity.HasKey(e => e.RouteId).HasName("PK__Routes__80979AADE2DF78CF");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
        });

        modelBuilder.Entity<RouteSegment>(entity =>
        {
            entity.HasKey(e => e.SegmentId).HasName("PK__RouteSeg__C680609B24DEC117");

            entity.HasOne(d => d.Route).WithMany(p => p.RouteSegments).HasConstraintName("FK_RouteSegments_Routes");
        });

        modelBuilder.Entity<Trip>(entity =>
        {
            entity.HasKey(e => e.TripId).HasName("PK__Trips__51DC711ED25668A7");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Status).HasDefaultValue("Scheduled");

            entity.HasOne(d => d.Driver).WithMany(p => p.Trips)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Trips_Driver");

            entity.HasOne(d => d.Route).WithMany(p => p.Trips)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Trips_Route");
        });

        modelBuilder.Entity<TripLocation>(entity =>
        {
            entity.HasKey(e => e.TripLocationId).HasName("PK__TripLoca__6D2C2137A53D73A7");

            entity.Property(e => e.RecordedAt).HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.Trip).WithMany(p => p.TripLocations).HasConstraintName("FK_TripLocations_Trip");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CCAC03ACDA06");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.UserType).WithMany(p => p.Users)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Users_UserTypes");
        });

        modelBuilder.Entity<UserProfile>(entity =>
        {
            entity.HasKey(e => e.UserProfileId).HasName("PK__UserProf__9E267F426973E2D1");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.User).WithOne(p => p.UserProfile).HasConstraintName("FK_UserProfiles_Users");
        });

        modelBuilder.Entity<UserType>(entity =>
        {
            entity.HasKey(e => e.UserTypeId).HasName("PK__UserType__40D2D8F64445C3F4");
        });

        modelBuilder.Entity<Vehicle>(entity =>
        {
            entity.HasKey(e => e.VehicleId).HasName("PK__Vehicles__476B54B200FE64A7");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.SeatsCount).HasDefaultValue(4);

            entity.HasOne(d => d.Driver).WithMany(p => p.Vehicles).HasConstraintName("FK_Vehicles_Driver");
        });

        modelBuilder.Entity<Weather>(entity =>
        {
            entity.HasKey(e => e.WeatherId).HasName("PK__Weather__0BF97BD58BF83CE7");

            entity.HasOne(d => d.Route).WithMany(p => p.Weathers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Weather_Route");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}