// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartTransportation.DAL.Models;

#nullable disable

namespace SmartTransportation.DAL.Migrations
{
    [DbContext(typeof(TransportationContext))]
    [Migration("20251025111147_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartTransportation.DAL.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<int>("BookerUserId")
                        .HasColumnType("int")
                        .HasColumnName("BookerUserID");

                    b.Property<DateTime>("BookingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("SeatsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("TripId")
                        .HasColumnType("int")
                        .HasColumnName("TripID");

                    b.HasKey("BookingId")
                        .HasName("PK__Bookings__73951ACDD89388C5");

                    b.HasIndex(new[] { "TripId" }, "IX_Bookings_TripID");

                    b.HasIndex(new[] { "BookerUserId" }, "IX_Bookings_UserID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.BookingPassenger", b =>
                {
                    b.Property<int>("BookingPassengerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BookingPassengerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingPassengerId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<bool>("CheckInStatus")
                        .HasColumnType("bit");

                    b.Property<int>("PassengerUserId")
                        .HasColumnType("int")
                        .HasColumnName("PassengerUserID");

                    b.Property<int?>("SeatNumber")
                        .HasColumnType("int");

                    b.HasKey("BookingPassengerId")
                        .HasName("PK__BookingP__34702EA702D62CCE");

                    b.HasIndex("PassengerUserId");

                    b.HasIndex(new[] { "BookingId" }, "IX_BookingPassengers_BookingID");

                    b.ToTable("BookingPassengers");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.BookingSegment", b =>
                {
                    b.Property<int>("BookingSegmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BookingSegmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingSegmentId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<int>("SegmentId")
                        .HasColumnType("int")
                        .HasColumnName("SegmentID");

                    b.HasKey("BookingSegmentId")
                        .HasName("PK__BookingS__586D1F1A5D2A763B");

                    b.HasIndex("SegmentId");

                    b.HasIndex(new[] { "BookingId" }, "IX_BookingSegments_BookingID");

                    b.ToTable("BookingSegments");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.MapLocation", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LocationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("GoogleAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("GooglePlaceId")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("GooglePlaceID");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<int>("SegmentId")
                        .HasColumnType("int")
                        .HasColumnName("SegmentID");

                    b.Property<int?>("StopOrder")
                        .HasColumnType("int");

                    b.HasKey("LocationId")
                        .HasName("PK__MapLocat__E7FEA4773DBDE9E4");

                    b.HasIndex(new[] { "SegmentId" }, "IX_MapLocations_SegmentID");

                    b.ToTable("MapLocations");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NotificationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E327044E76E");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PaymentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("EGP");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__9B556A58CD4B6218");

                    b.HasIndex("BookingId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RatingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int")
                        .HasColumnName("TripID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("RatingId")
                        .HasName("PK__Ratings__FCCDF85C0B0A9020");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RouteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RouteId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("EndLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EstimatedTimeMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsCircular")
                        .HasColumnType("bit");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RouteType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StartLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("TotalDistanceKm")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("RouteId")
                        .HasName("PK__Routes__80979AADE2DF78CF");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.RouteSegment", b =>
                {
                    b.Property<int>("SegmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SegmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SegmentId"));

                    b.Property<decimal?>("DistanceKm")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("EndPoint")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EstimatedMinutes")
                        .HasColumnType("int");

                    b.Property<int>("RouteId")
                        .HasColumnType("int")
                        .HasColumnName("RouteID");

                    b.Property<int>("SegmentOrder")
                        .HasColumnType("int");

                    b.Property<string>("StartPoint")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SegmentId")
                        .HasName("PK__RouteSeg__C680609B24DEC117");

                    b.HasIndex("RouteId");

                    b.ToTable("RouteSegments");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TripID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripId"));

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("DriverId")
                        .HasColumnType("int")
                        .HasColumnName("DriverID");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("PricePerSeat")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("RouteId")
                        .HasColumnType("int")
                        .HasColumnName("RouteID");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Scheduled");

                    b.HasKey("TripId")
                        .HasName("PK__Trips__51DC711ED25668A7");

                    b.HasIndex(new[] { "DriverId" }, "IX_Trips_DriverID");

                    b.HasIndex(new[] { "RouteId" }, "IX_Trips_RouteID");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.TripLocation", b =>
                {
                    b.Property<int>("TripLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TripLocationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripLocationId"));

                    b.Property<string>("GoogleAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("GooglePlaceId")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("GooglePlaceID");

                    b.Property<decimal?>("Heading")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<decimal?>("Speed")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("TripId")
                        .HasColumnType("int")
                        .HasColumnName("TripID");

                    b.HasKey("TripLocationId")
                        .HasName("PK__TripLoca__6D2C2137A53D73A7");

                    b.HasIndex(new[] { "TripId" }, "IX_TripLocations_TripID");

                    b.ToTable("TripLocations");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("int")
                        .HasColumnName("UserTypeID");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCAC03ACDA06");

                    b.HasIndex("UserTypeId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534CECA4B42")
                        .IsUnique();

                    b.HasIndex(new[] { "UserName" }, "UQ__Users__C9F284565049D52A")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.UserProfile", b =>
                {
                    b.Property<int>("UserProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserProfileID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserProfileId"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DriverLicenseExpiry")
                        .HasColumnType("date");

                    b.Property<string>("DriverLicenseNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("DriverRating")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<string>("FullName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDriver")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDriverVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("UserProfileId")
                        .HasName("PK__UserProf__9E267F426973E2D1");

                    b.HasIndex(new[] { "UserId" }, "UQ__UserProf__1788CCAD0CBF73C7")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.UserType", b =>
                {
                    b.Property<int>("UserTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserTypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserTypeId")
                        .HasName("PK__UserType__40D2D8F64445C3F4");

                    b.ToTable("UserTypes");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VehicleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("DriverId")
                        .HasColumnType("int")
                        .HasColumnName("DriverID");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("PlateNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SeatsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(4);

                    b.Property<DateOnly?>("VehicleLicenseExpiry")
                        .HasColumnType("date");

                    b.Property<string>("VehicleLicenseNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VehicleMake")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VehicleModel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("VehicleYear")
                        .HasColumnType("int");

                    b.HasKey("VehicleId")
                        .HasName("PK__Vehicles__476B54B200FE64A7");

                    b.HasIndex("DriverId");

                    b.HasIndex(new[] { "PlateNumber" }, "UQ__Vehicles__03692624491BD79E")
                        .IsUnique()
                        .HasFilter("[PlateNumber] IS NOT NULL");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.Weather", b =>
                {
                    b.Property<int>("WeatherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WeatherID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeatherId"));

                    b.Property<string>("Condition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Humidity")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("RouteId")
                        .HasColumnType("int")
                        .HasColumnName("RouteID");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateOnly>("WeatherDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("WindSpeed")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("WeatherId")
                        .HasName("PK__Weather__0BF97BD58BF83CE7");

                    b.HasIndex(new[] { "RouteId" }, "IX_Weather_RouteID");

                    b.ToTable("Weather");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.Booking", b =>
                {
                    b.HasOne("SmartTransportation.DAL.Models.User", "BookerUser")
                        .WithMany("Bookings")
                        .HasForeignKey("BookerUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_User");

                    b.HasOne("SmartTransportation.DAL.Models.Trip", "Trip")
                        .WithMany("Bookings")
                        .HasForeignKey("TripId")
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Trip");

                    b.Navigation("BookerUser");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.BookingPassenger", b =>
                {
                    b.HasOne("SmartTransportation.DAL.Models.Booking", "Booking")
                        .WithMany("BookingPassengers")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BookingPassengers_Booking");

                    b.HasOne("SmartTransportation.DAL.Models.User", "PassengerUser")
                        .WithMany("BookingPassengers")
                        .HasForeignKey("PassengerUserId")
                        .IsRequired()
                        .HasConstraintName("FK_BookingPassengers_User");

                    b.Navigation("Booking");

                    b.Navigation("PassengerUser");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.BookingSegment", b =>
                {
                    b.HasOne("SmartTransportation.DAL.Models.Booking", "Booking")
                        .WithMany("BookingSegments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BookingSegments_Booking");

                    b.HasOne("SmartTransportation.DAL.Models.RouteSegment", "Segment")
                        .WithMany("BookingSegments")
                        .HasForeignKey("SegmentId")
                        .IsRequired()
                        .HasConstraintName("FK_BookingSegments_Segment");

                    b.Navigation("Booking");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.MapLocation", b =>
                {
                    b.HasOne("SmartTransportation.DAL.Models.RouteSegment", "Segment")
                        .WithMany("MapLocations")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MapLocations_Segment");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.Notification", b =>
                {
                    b.HasOne("SmartTransportation.DAL.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.Payment", b =>
                {
                    b.HasOne("SmartTransportation.DAL.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Payments_Booking");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.Rating", b =>
                {
                    b.HasOne("SmartTransportation.DAL.Models.Trip", "Trip")
                        .WithMany("Ratings")
                        .HasForeignKey("TripId")
                        .IsRequired()
                        .HasConstraintName("FK_Ratings_Trip");

                    b.HasOne("SmartTransportation.DAL.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Ratings_User");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.RouteSegment", b =>
                {
                    b.HasOne("SmartTransportation.DAL.Models.Route", "Route")
                        .WithMany("RouteSegments")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RouteSegments_Routes");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.Trip", b =>
                {
                    b.HasOne("SmartTransportation.DAL.Models.User", "Driver")
                        .WithMany("Trips")
                        .HasForeignKey("DriverId")
                        .IsRequired()
                        .HasConstraintName("FK_Trips_Driver");

                    b.HasOne("SmartTransportation.DAL.Models.Route", "Route")
                        .WithMany("Trips")
                        .HasForeignKey("RouteId")
                        .IsRequired()
                        .HasConstraintName("FK_Trips_Route");

                    b.Navigation("Driver");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.TripLocation", b =>
                {
                    b.HasOne("SmartTransportation.DAL.Models.Trip", "Trip")
                        .WithMany("TripLocations")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TripLocations_Trip");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.User", b =>
                {
                    b.HasOne("SmartTransportation.DAL.Models.UserType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_UserTypes");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.UserProfile", b =>
                {
                    b.HasOne("SmartTransportation.DAL.Models.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("SmartTransportation.DAL.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserProfiles_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.Vehicle", b =>
                {
                    b.HasOne("SmartTransportation.DAL.Models.User", "Driver")
                        .WithMany("Vehicles")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Vehicles_Driver");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.Weather", b =>
                {
                    b.HasOne("SmartTransportation.DAL.Models.Route", "Route")
                        .WithMany("Weathers")
                        .HasForeignKey("RouteId")
                        .IsRequired()
                        .HasConstraintName("FK_Weather_Route");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.Booking", b =>
                {
                    b.Navigation("BookingPassengers");

                    b.Navigation("BookingSegments");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.Route", b =>
                {
                    b.Navigation("RouteSegments");

                    b.Navigation("Trips");

                    b.Navigation("Weathers");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.RouteSegment", b =>
                {
                    b.Navigation("BookingSegments");

                    b.Navigation("MapLocations");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.Trip", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Ratings");

                    b.Navigation("TripLocations");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.User", b =>
                {
                    b.Navigation("BookingPassengers");

                    b.Navigation("Bookings");

                    b.Navigation("Notifications");

                    b.Navigation("Ratings");

                    b.Navigation("Trips");

                    b.Navigation("UserProfile");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("SmartTransportation.DAL.Models.UserType", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
